title: <p align="center">Tiklu Ganguly</p
logo: /assets/img/logo1.jpg
description: <p align="center">
  <a href="https://www.linkedin.com/in/tikluganguly/">LinkedIn</a> |
  <a href="https://github.com/tikluganguly">GitHub</a>

  <br>
  I am a software architect working on technologies like
  dotnet, Azure, Dynamics 365 Customer Engagement, Data Analytics, AI/ML
  etc. I have started professionally coding from 1999. Over the years I have
  worked with many large public sector companies and governments.
  <br>
  </p>

theme: jekyll-theme-minimal
